# use switchdn.yml

PHENOMAP_PLUS:
  [
    [0, 1, 0.7],
    [1, 1, 0.3],
    [1, 40, -0.5],

    [0, 15, 0.7],
    [15, 15, 0.3],
    [15, 41, -0.5],

    [0, 43, 0.7],
    [43, 43, 0.3],
    [43, 2, -0.1],

    [0, 45, 0.7],
    [45, 45, 0.3],
    [45, 13, -0.1],
  ]
